In [1]:
import pandas as pd

In [2]:
readtest1 = pd.read_csv("./clean_csv/clean_en_list.csv")
readtest1

                   value  count
0       ('BMW', 'Alpha')   2479
1       ('SUV', 'Alpha')   4046
2       ('The', 'Alpha')   1009
3       ('FTA', 'Alpha')    405
4        ('EV', 'Alpha')    503
..                   ...    ...
311     ('oid', 'Alpha')    174
312     ('aid', 'Alpha')    230
313  ('krhttp', 'Alpha')    999
314      ('FH', 'Alpha')    128
315   ('THAAD', 'Alpha')    130

[316 rows x 2 columns]

In [6]:
readtest1['value'].value_counts().sum()

316

In [3]:
readtest1.sort_values(by ='count', ascending=False)

                  value  count
35     ('the', 'Alpha')   4097
1      ('SUV', 'Alpha')   4046
82      ('to', 'Alpha')   2658
34      ('of', 'Alpha')   2598
0      ('BMW', 'Alpha')   2479
..                  ...    ...
191  ('right', 'Alpha')    102
179  ('Level', 'Alpha')    102
11      ('gm', 'Alpha')    101
111     ('RC', 'Alpha')    101
288    ('WWE', 'Alpha')    101

[316 rows x 2 columns]

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/lab14/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [7]:
from nltk.corpus import stopwords

stops = set(stopwords.words("english"))
#words = [w for w in words if not w in stops]

In [4]:
old_values = list(readtest1['value'])
len(old_values), type(old_values)

(316, list)

In [8]:
old_values[0]

"('BMW', 'Alpha')"

In [34]:
import re
patt = re.compile("'.*'\b")
re.findall(patt, old_values[0])

[]

In [10]:
old_values = [word for word, tag in old_values if not word in stops]
len(old_values), old_values[0]

ValueError: too many values to unpack (expected 2)

In [ ]:


df = pd.Dataframe(
    values = 
    )

In [17]:
students = [ ('Jack', 34, 'Sydney') ,
             ('Riti', 41, 'Delhi' ) ,
             ('Aadi', 16, 'New York') ,
             ('Riti', 22, 'Delhi' ) ,
             ('Riti', 35, 'Delhi' ) ,
             ('Riti', 40, 'Mumbai' )
              ]
# Create a DataFrame object
dfObj = pd.DataFrame(students, columns=['Name', 'Marks', 'City'], index=['b', 'a', 'f', 'e', 'd', 'c'])
dfObj

   Name  Marks      City
b  Jack     34    Sydney
a  Riti     41     Delhi
f  Aadi     16  New York
e  Riti     22     Delhi
d  Riti     35     Delhi
c  Riti     40    Mumbai

In [1]:
removed_ngram=[]
word1='w1'
word2='w2'

In [5]:
removed_ngram.append((word1+" "+word2))

In [6]:
removed_ngram

['w1 w2', 'w1 w2']

In [7]:
import pandas as pd
tryy = pd.Series(removed_ngram)
vc = tryy.value_counts()

In [8]:
newnew=[]
for bigram, cnt in vc.items():
    newnew.append((bigram, cnt))

In [9]:
newnew

[('w1 w2', 2)]

# test 9/29

In [18]:
from nltk.tokenize import sent_tokenize
import pandas as pd
import re

In [19]:
awarness = pd.read_excel('awarness_blog&cafe.xlsx')#, encoding='utf-8')\
docs = awarness['all_text']

In [20]:
awarness

                                                all_text
0      서울 각 구별 자동차 브랜드와 비교*부동산스터디 게시판 운영가이드\nhttps://...
1      픽업트럭 시장도 '후끈'…한국지엠 콜로라도로 도전장픽업트럭 시장도 '후끈'…한국지엠...
2      현대차가 해결했다..성능 업그레이드 OTA 불법현대차가 해결했다..성능 업그레이드 ...
3      자동차 헤드램프 습기,고장인가요?차량을 운행하다보면 차량 내부나 외부에 \n습기가 ...
4      1986 Chevrolet Caprice Brougham1986 쉐보레 카프리스 브...
...                                                  ...
11159  자율 주행 자동차를 대상으로 한 위험 분석 및 Risk 평가 방안 1ADAS 능동형...
11160  nan입력 20200702 0753 미국의 전기자동차 기업인 테슬라가 시가총액 세계...
11161  대형 마트 주차장을 자동차 영화관으로 쓴다면코로나 바이러스 감염증19코로나19 확산...
11162  이번달부터는 운전자가 운전대를 잡지 않아도이번달부터는 운전자가 운전대를 잡지 않아도...
11163  끝없이 치솟고 있는 테슬라 주가feat Covid19Point 1 2020년 테슬라...

[11164 rows x 1 columns]

In [4]:
doc = awarness['all_text'].iloc[11162]
doc

'이번달부터는 운전자가 운전대를 잡지 않아도이번달부터는 운전자가 운전대를 잡지 않아도자동으로 차로유지 기능도 되고 알아서 멈추는 자율주행자동차의 출시판매가 가능해진다자동차 및 자동차부품의 성능과 기준에 관한 규칙을 개정해서안전기준을 부분 자율주행차레벨 3 수준으로 끌어올렸다고 하니 가능하다기존의 안전기준레벨 2은 차로유지기능을 작동시켜도 운전자가 운전대에서 손을 떼면 경고음이 울리는 경보기 수준이지만 이제는  운전자가 다른 짓으로 바빠서 손을 대지 않아도  주행이 가능한 단계까지 허용한 것이다레벨 3부터는 자율주행차로 분류된다 자율주행 자동차는 기본적으로 3가지 센서를 이용하여 가능하다먼저 카메라카메라는 시각적인 데이터를 획득한다자율 주행 차량은 전방 후방 좌우측의 카메라를 사용하여360도 시야를 확보 할 수 있다일부 카메라는 상당히 넓은 화각 120도을 가지고 있기도 하다어안 렌즈 카메라가 장착되어있다면 차량 뒤의 모든 모습을상당히 넓은 부분을 볼 수있고 이에 대한 데이터를 획득한다카메라는 정확한 비주얼 데이터를 제공하지만 약간의 제한이 있다특히 정확한 위치 계산을 시작하려면 거리를 판단하기 위해서는2 차원적인 데이터가 필요하다그리고 카메라 센서가 비 안개 또는 밤과 같이 시인성이낮은 조건에서 물체를 감지하기 어렵고 특히 낮은 위치의석양빛을 마주 보면 사물의 인식이 제대로 안되는 단점이 있다 이러한 단점을 극복하기 위해서 레이더를 장착한다레이더 센서는 시인성의 한계를 가진 카메라를 보완한다항공기 기상 형성 및 선박 감지를 해서 오래전부터 일상적으로 이용되던기술이지만 소형화와 내구성이 중요해진다전파를 펄스로 전송하고 일련의 펄스파가 물체에 부딪혀서돌아오면 수신기로 감지를 하여 속도 및 위치 데이터를 획득한다레이더 센서는 모든 각도에서 물체를 감지하지만다른 차량의 유형을 구별 할 수는 없는 한계가 있다그래서 추가로 필요한 것이 Lidar이다이는 레이더와 같으나 그 신호원이 전자파가 아닌 레이저이다LiDAR는 레이더와 함께 자율 주행 차량의 거리 감지를 실행하는 중요한 광전자 기술이다LiDAR 센서는 앞의 상황에 대한 그림을 그리는데 도움이된다레이저 펄스를 보내고 반사되는 수신 신호의 시간을 계산하여 거리를 측정하는데LiDAR는 결국 자율자동차에 3D 정보를 제공하는 셈이다특히 주변 차량과 보행자의 형태나 위치 데이터를 제공한다 그리고 중요한 GPS를 이용한 자신의 위치에 대한 데이터이것은 이미 많은 차량에 설치된 네비게이터를 통해서 획득하게 된다아울러 정보통신기술에 의한 각 교통상황에 대한 정보가 더해지면완벽하게 자율주행을 하게 된다각종 상황에 따라서 이러한 센서들의 데이터를 종합하여 판단하고그에 따라서 실제로 차량을 운행을 위한 제어는 고성능의 컴퓨터모듈이하게 된다 그렇다고 하여 사람이 내는 사고를 자율자동차가 완벽하게피할 수 있는 것은 아니다환경적인 요인에 의해서 충분한 데이터를 카메라 레이더 Lidar GPS가획득하지 못하는 경우도 있고 차량내의 전원의 불안정으로 인해서센서와 컴퓨터가 제대로 작동하지 못하는 경우도 생길 수 있다 실제로 미국의 테슬라 자율주행차는 사고를 내서 운전자가 사망한경우도 생겼다그러므로 자율주행을 하더라도 100 운전을 차량에게 맡기는 것은자제하는 것이 중요하다'

In [6]:
doc = re.sub("[ㄱ-ㅎㅏ-ㅣ]", " ", doc)
doc = doc.lower()
sent = sent_tokenize(doc)
sent

['이번달부터는 운전자가 운전대를 잡지 않아도이번달부터는 운전자가 운전대를 잡지 않아도자동으로 차로유지 기능도 되고 알아서 멈추는 자율주행자동차의 출시판매가 가능해진다자동차 및 자동차부품의 성능과 기준에 관한 규칙을 개정해서안전기준을 부분 자율주행차레벨 3 수준으로 끌어올렸다고 하니 가능하다기존의 안전기준레벨 2은 차로유지기능을 작동시켜도 운전자가 운전대에서 손을 떼면 경고음이 울리는 경보기 수준이지만 이제는  운전자가 다른 짓으로 바빠서 손을 대지 않아도  주행이 가능한 단계까지 허용한 것이다레벨 3부터는 자율주행차로 분류된다 자율주행 자동차는 기본적으로 3가지 센서를 이용하여 가능하다먼저 카메라카메라는 시각적인 데이터를 획득한다자율 주행 차량은 전방 후방 좌우측의 카메라를 사용하여360도 시야를 확보 할 수 있다일부 카메라는 상당히 넓은 화각 120도을 가지고 있기도 하다어안 렌즈 카메라가 장착되어있다면 차량 뒤의 모든 모습을상당히 넓은 부분을 볼 수있고 이에 대한 데이터를 획득한다카메라는 정확한 비주얼 데이터를 제공하지만 약간의 제한이 있다특히 정확한 위치 계산을 시작하려면 거리를 판단하기 위해서는2 차원적인 데이터가 필요하다그리고 카메라 센서가 비 안개 또는 밤과 같이 시인성이낮은 조건에서 물체를 감지하기 어렵고 특히 낮은 위치의석양빛을 마주 보면 사물의 인식이 제대로 안되는 단점이 있다 이러한 단점을 극복하기 위해서 레이더를 장착한다레이더 센서는 시인성의 한계를 가진 카메라를 보완한다항공기 기상 형성 및 선박 감지를 해서 오래전부터 일상적으로 이용되던기술이지만 소형화와 내구성이 중요해진다전파를 펄스로 전송하고 일련의 펄스파가 물체에 부딪혀서돌아오면 수신기로 감지를 하여 속도 및 위치 데이터를 획득한다레이더 센서는 모든 각도에서 물체를 감지하지만다른 차량의 유형을 구별 할 수는 없는 한계가 있다그래서 추가로 필요한 것이 lidar이다이는 레이더와 같으나 그 신호원이 전자파가 아닌 레이저이다lidar는 레이더와 함께 자율 주행 차량의 거리 감지를 실행하는 중요한 광전자 기술이다lidar 센서는 앞의 상황에 대한 그림을 그리는데 도움이된다레이저 펄스를 보내고 반사되는 수신 신호의 시간을 계산하여 거리를 측정하는데lidar는 결국 자율자동차에 3d 정보를 제공하는 셈이다특히 주변 차량과 보행자의 형태나 위치 데이터를 제공한다 그리고 중요한 gps를 이용한 자신의 위치에 대한 데이터이것은 이미 많은 차량에 설치된 네비게이터를 통해서 획득하게 된다아울러 정보통신기술에 의한 각 교통상황에 대한 정보가 더해지면완벽하게 자율주행을 하게 된다각종 상황에 따라서 이러한 센서들의 데이터를 종합하여 판단하고그에 따라서 실제로 차량을 운행을 위한 제어는 고성능의 컴퓨터모듈이하게 된다 그렇다고 하여 사람이 내는 사고를 자율자동차가 완벽하게피할 수 있는 것은 아니다환경적인 요인에 의해서 충분한 데이터를 카메라 레이더 lidar gps가획득하지 못하는 경우도 있고 차량내의 전원의 불안정으로 인해서센서와 컴퓨터가 제대로 작동하지 못하는 경우도 생길 수 있다 실제로 미국의 테슬라 자율주행차는 사고를 내서 운전자가 사망한경우도 생겼다그러므로 자율주행을 하더라도 100 운전을 차량에게 맡기는 것은자제하는 것이 중요하다']

In [7]:
def sentences(index):
    doc = awarness['all_text'].iloc[index]
    doc = re.sub("[ㄱ-ㅎㅏ-ㅣ]", " ", doc)
    doc = doc.lower()
    sent = sent_tokenize(doc)
    return (len(sent), sent)

In [9]:
sentences(1)

(19,
 ["픽업트럭 시장도 '후끈'…한국지엠 콜로라도로 도전장픽업트럭 시장도 '후끈'…한국지엠 콜로라도로 도전장\n[동영상재생:nvp1][앵커멘트]레저 문화가 확산되면서 실용성이 뛰어난 픽업트럭을 찾는 소비자들도 늘어나고 있는데요.",
  '한국지엠이 suv와 트럭의 장점을 모두...\nnews.mtn.co.kr\n[앵커멘트]\n레저 문화가 확산되면서 실용성이 뛰어난 픽업트럭을 찾는 소비자들도 늘어나고 있는데요.',
  '한국지엠이 suv와 트럭의 장점을 모두 갖춘 모델을 앞세워 국내 픽업트럭 시장에 도전장을 던졌습니다.',
  '보도에 김승교 기자입니다.',
  '[기사내용]\n가파른 경사로를 거침없이 올라가고, 뒷바퀴가 들릴 정도로 울퉁불퉁한 오프로드도 힘차게 빠져나옵니다.',
  '일반 자동차는 움직이기 힘든 진흙탕은 물론 바퀴가 잠길 만한 깊은 물웅덩이도 가뿐히 통과합니다.',
  '한국지엠이 공개한 콜로라도입니다.',
  '정통 픽업트럭 모델답게 거친 오프로드를 자유자재로 주행할 수 있고, 최대 3.2톤에 달하는 초대형 카라반도 거뜬하게 견인할 수 있습니다.',
  '짐을 운반하는 용도로만 사용됐던 픽업트럭은 최근 다양한 여가 문화가 발달하면서 인기를 끌고 있습니다.',
  '특히 캠핑과 서핑 등 부피가 큰 짐을 실을 수 있는 적재 공간과 도심 주행을 소화할 수 있는 정숙성까지 갖춰 픽업트럭을 찾는 수요는 더욱 가파르게 증가하고 있습니다.',
  '2017년 판매된 픽업트럭은 2만2900여대.',
  '이듬해 4만2000여대로 80% 이상 폭발적으로 증가한 이후 지난해까지 2년 연속 4만대 이상 판매됐습니다.',
  '국내 픽업트럭 시장에 도전장을 던진 콜로라도의 경쟁 상대는 시장 점유율 90% 이상을 차지하고 있는 쌍용차의 렉스턴 스포츠.',
  '한국지엠은 픽업트럭의 본고장인 미국 시장에서 연간 10만대 이상 판매되고 있는 상품성과 100년 넘게 쌓인 기술 노하우를 앞세워 국내 픽업트럭 시장을 공략한다는 계획입니다.',
  '카허 카젬 / 한국지엠 사장\n고객들이 트럭에 대한 기대가 커진 만큼, 신형 콜로라도는 더욱 풍성해진 트림과 편의사양을 제공하며 고객들의 라이프 스타일에 따라 차량을 선택할 수 있도록 선택지를 넓혔습니다.',
  '만능 suv로 소비자들의 마음을 사로잡은 픽업트럭.',
  '콜로라도가 커지고 있는 국내 시장에서 존재감을 드러내며 시장 공략에 성공할 수 있을지 관심이 쏠립니다.',
  '머니투데이방송 김승교입니다.',
  '김승교 머니투데이방송 mtn 기자 \n★ 쉐보레 콜로라도 네이버 대표 동호회 ★ 클럽콜로라도 ★\n콜로라도/쉐보레/쉐보레콜로라도/콜로라도출시/콜로라도가격/콜로라도시승기/콜로라도연비/\n콜로라도색상/콜로라도옵션/콜로라도구입/콜로라도구매/콜로라도수입/콜로라도동호회'])

In [11]:
from konlpy.tag import Kkma
from konlpy.utils import pprint
kkma = Kkma()

def kma_sent(index):
    pprint((len(kkma.sentences(awarness['all_text'].iloc[index])),kkma.sentences(awarness['all_text'].iloc[index])))

In [12]:
sentences(15)

(97,
 ['산소센서, 촉매효율 저하?',
  '엔진경고등?',
  '흡기청소?의 진실, 직접 경험한 스토리입니다.저의 알페온 증상에 따른 이야기 입니다.',
  '2020년 9월 7일(월)\n저는 올해초 페오니 3.0을 입양해서 타던중..\n지난주 촉매효율저하라는 많은분들이 경험하신 엔진경고등을 만나고나서!!!',
  '영등포 직영사업소, 강서 정비사업소를 들러..촉매를 갈아야 한다는 소리와 어마어마한 비용에 다시한번 놀라고 나서,\n평소 그원인이 무엇이길래??',
  '갈아도 또 얼마지나지 않아...이런저런 정비를 한다는 소리를 많은분들에게서 들었기에..\n블로그를 검색해서 촉매를 재생한다는 업소에 전화도 해보고..다른 정비 사례도 블로그로 보고\n이래저래 해봐도...답이 없어서...바로 알페온 본카페에 가입을 하고 찾아봐도 다들 어려움을 겪고 계시기에..\n왜 카본이 쌓이지?',
  '왜 흡기가 저렇게 시커먼거야?',
  '왜 산소센서가 오작동을 하는거야?',
  '끊임없는 궁굼증과 고민속에서....\n여기저기 뒤지던중...!!!',
  '유튜브에서 권영호 라는 분의 영상을 보게 됩니다.',
  'https://youtu.be/vawt4rku1cy\n그리고 하나더..이영상을 보게 됩니다.',
  'https://youtu.be/tiahybcfapk\n그리고 저는 직감적으로 늦음 밤시간 잠도 뒤로한체  바로 이분과 이야기를 해야겠다라고 결심을 합니다.',
  '평상시 저는...\n흡기 카본이 왜 그렇게 검게 쌓이는지?..대한민국 디젤차가 다 저렇다면 도대체 현기차는 무엇을 한것인지?',
  '점화플러그를 갈아도 연료효율 저하가 왜 생기는지?',
  '부조는 왜 생기는건지?',
  '흡기 클리닝을 해도 왜 또 쌓이는건지.. 차는 원래 다 저런건지..라는 여기 모든분들이 가지고 계신 의문점을 저역시도 가지고 있었던 터라...\n권영호 샘의 위 영상을 두편 보고...결국 그 답은 냉각수에 있음을 알게되었습니다.',
  '그래서 지난주 금요일 권영호 선생님이 운영하시는 영호자동차가 군산에서 화성으로 정비사업소 이사를 하셨다는 것을 알게되었고...바로 전화드려 예약을 한후에..',
  '드디어..!!',
  '오늘 권영호 선생님 화성정비사업소를 다녀왔습니다.',
  '저를 오래 기다리고 계셨더라구요.',
  '이사한지 얼마 안되서 아직 직원을 못 뽑으셨고, 태풍으로 비도 오고해서 아무도 없는 터라, \n저와 단둘이서 정비를 무려 5시간동안 이런 저런 이야기를 나누면서 정비를 해주셨는데요\n(정비하기 전에 저를 앉혀놓으시고 2시간을 정비학 강의??',
  '를 먼저 충분히 해주시네요..\n세상에 이런 정비사가 대한민국에 있었던가 싶었습니다~  )\n마치고 나서 함께 저녁식사를 하면서 그분의 미국 유학시절 이야기부터 정비사들을 대상으로 세미나 강의를 하셨던 내용들 등등을 듣게 됩니다.',
  '암튼 냉각수를 교환하지는 않았습니다.',
  '냉각수 청소를 필터를 통해서 하면서 비중을 조정하고 ph농도를 맞추어서 엔진의 온도를 최적화 하는 작업만 3시간 하였습니다.',
  '(비중을 맞추면서 ph를 조정하는것이 결국 그분의 노하우였습니다.)',
  '냉각수내에 있는 때와 먼지를 필터링하고, 비중계를 함께 보면서 맞춰주시고, 산도를 조정하여 차의 냉각수가 지나가는 통로에 부식이나 천공이 생기지 않도록 ph조절 약품을 통해 농도를 중성에 맞추는 작업을 하였습니다.',
  '(작업전 제 차의 이력으로 입양전에 흡기청소, 점화플러그 교체..써모스텟 교체 등 그리고 입양후 지난주 엔진오일 5w30 교체, 밧데리 최근 교체..등을 말씀드렸고요...)\n그결과는 놀라웠습니다.',
  '작업중에도 엔진이 부드러워지는 것을 샘과 함께 느낄수 있었습니다.',
  '맞다고 하시네요.',
  '엔진의 온도가 낮아지니..여러가지로 차가 부드러워졌습니다.',
  '정비를 마치고 제 차로 선생님과 함께 식당으로 이동하면서도 함께 느끼고..\n식사를 마치고 김포 집을 오면서 약 50km 정도 운행을 하면서 느낀점은 진작에 왜 이런걸 우리는 몰랐을까 였습니다\n1.',
  '일단 온도계이지의 바늘이 예전보다 낮은 지점에 있다.',
  '2.',
  '변속시 충격이 거의 없어졌다.',
  '변속타이밍이 좋아졌습니다.',
  '(변속시 알피엠이 줄어들었다.)',
  '3.',
  '예전에는 악셀을 밟아도 느린 반응으로 인해서 늘 끼어들기를 허용하는 관용을 배풀었는데요~  \n   이제는 낮은 rpm에서도 끼어들기 허용?',
  '오늘 하루는 일단 용납을 안했습니다~\n   즉, 가속력이 좋아졌다는 거죠?',
  '4.',
  '또 제가 지난달 언젠가부터 저속에서 악셀을 떼면 퉁!',
  '다시 밟으면 퉁!',
  '이렇게 악셀을 밟고 놓을때마다 퉁퉁 하는 충격이 있었거든요..이것이 저는 엔진 마운팅볼트(미미)의 불량으로 생각을 해본적도 있었는데..\n제가 느낀것은 엔진 점화효울 상승으로 악셀을 밟고 뗄때나 브레이크를 밟고 뗄때의 엔진반응이 아주 좋아졌다는것을 느낄수 있었습니다.',
  '5.',
  '아직은 더 지켜봐야 하지만 엔진경고등 뿐아니라 어떤 고장코드도 안뜬다 입니다.',
  '몰론 더 지켜봐야 하겠지만요....\n여기서 잠시!',
  '** 비용을 제가 말씀못드리는 것이....\n비용은 비교적 좀 됩니다.',
  '그러나!!',
  '그분이 5시간동안 저에게 말씀해주신 내용은 그 이상의 가치를 저는 받았다고 생각을 하기에 아깝다고 생각하지는 않습니다.',
  '연비가 좋아지고, 다른 곳 고장 안나면 저는 충분히 그 가치를 했다고 생각해서요~ **\n권선생님의 말씀..\n"냉각수는 옷, 엔진오일은 피\n우리나라 처럼 따듯한 나라에서 -45도에 맞춘 5:5 비중의 냉각수는 열대지방에서 겨울옷을 입고있는것과 같다.',
  '그러면 체온을 유지하기 위해 얼마나 많은 산소와 땀을 흘리면서 생활을 하겠어요....그옷을 벗어 던지지 않으면 모든 병의 근원이 된다"\n사진은 정비후 50km 운행후에 제 계기판 사진입니다.',
  '제가 예전 사진이 없는데..지금 여러분들의 계기판의 온도와 얼마나 다른가요?',
  '읽어주셔서 감사합니다.',
  '권영호 정비사업소는 경기도 화성시 봉담음 수기리 125-7\nhttp://naver.me/fjrwgwsp\n031-468-0188 / 010.4781-0302\n9월 8일(수) 둘째날 경험\n저는 그냥 서울 테헤란로에서 근무하고 있는 평범한 일반인인데요.~ \n그동안 우리가 알고있던 모든 증상의 90%는 냉각수와 엔진오일에 있었네요..\n제가 오늘도 차를 타면서 느낀점은..\n고작 냉각수 하나 건드려서.',
  '비중조정과 ph 중성화 하여 .엔진 온도를 낮춘것 뿐인데..\n브레이크 작동, 미션 작동, 가속능력, 변속충격 등 모든것이 좋아졌습니다.',
  '이런 노하우를 우리 모든 회원들이 함께 공유했으면 하는 바랩입니다.',
  '불완전연소, 카본, 촉매, 산소센서 등에서의 신호는 모두 엔진온도 상승으로 인한 결과물이었던 거 였다는 건데요\n이번주는 어제 정비후 연비를 측정해보고 있고요...\n다음달 다시 권영호 샘 방문해서 엔진오일도 함 갈아보려 합니다  \n촉매 이상, 시동이상 등등 괜한 코일, 플러그, 센서, 촉매 비싼돈 주고 교환하기 전에 꼭 한번 해보세요..\n진짜 대박입니다요~  \n하루빨리 수많은 미해결 증상이 없어질 그날을 위해 공유하겠습니다오~!',
  '제목 보고 들어와봤는데요..\n저는 이어시타고 팄는데 혹시나 가봐도 될지 모르겠네요..\n저도 요즘 페온이가 조금 엑셀을 밟을 때 뭔가 철사가 끊어지는 듯한 느낌의 소리(?',
  ')가 나는 게 조금 느껴져서요.. 진짜 너무 할말이 많은데요..꼭 함 가보세요...김포에서 왔다던 제이야기를 하면 아실겁니다.',
  '귀한 정보 감사합니다.',
  '저도 함 해보겠습니다.',
  '냉각수 중요성 맞습니다\n냉각수라인 청소와 농도를 다시 맞추는 작업이겠네요\n미션오일도 냉각수 라지에이터를 통해서 냉각/가열되니까 미션성능과도 상관있지않을까 하는 뇌피셜입니다   \n쉐보레차는 냉각수온도가 높아서 100도를 넘는경우가 많다는 글이 많아서 그런가부다 했는데 제차 확인해보니 85도에서 상당히 가혹하게달려도 100도가 안된다는걸 확인한후 의문점이 생겼습니다만 저처럼 낮은경우가 별로 없는듯해서 오히려 제차가 이상한가 생각도 하게되네요     네 맞습니다.',
  '냉각수 고무관에 붙은 때를 벗기면 냉각효율이 좋아진다고 합니다.',
  '냉각수는 교환하는것이 아니라 순환기를 통해 청소만 하면 된다고 하시고.. 실제 청소후 맑은 홍차가 되더라고요\n엔진온도가 낮으면 각종 고무부품의 부풀어오름과 경화를 방지하게 되니 이역시 비용절감..\nph농도가 낮아서 산성이되면..부식과 천공이 생기고..(뇌출혈   )\nph농도가 높아서 알칼리가 되면 혈전이 쌓이게되서..(동맥경화.)',
  '이런거라고 하시네요\n그래서 한국 기후에 맞는 농도도 중요하심나 ph농도 역시 부품의 내구성과 유지에 아주 중요하다는 말씀도 함께 들었습니다.',
  '실제 맞고 공감하는 내용들이었습니다~  좋은글 잘봤습니다.',
  '가보고싶은 마음이 저절로드네요.',
  '혹시 비용이 얼마인지 일수있을까요 직접 전화해보시면 알려주실겁니다^^ 저도 그랬거든요... 냉각수 관리 중요합니다.',
  '전 예전차에 냉각수 교환 및\n크리닝으로 전체적인 효과를 봐서 그런지 냉각수 중요하다 생각드네요.',
  '물론 페온이도 관리를 잘 해서 그런지 작년에 중고로\n가져와 알피엠 풀로 다녀도\n아직 경고등 한번 본적이 없네요.',
  '좋은글이네요.냉각수와 오일류만 잘 관리해도 8할은 먹고 가는거죠.',
  '안전운전하세요~ 성의있는 후기 잘 보았습니다\n회원님들이 냉각수 중요성을 많이 알게 될 것 같습니다 저도 엔진출력부족 부조 꿀렁임 관련해서 이미 앞전에 방문해서 점검받았고 견제 받았네요 그런데 금액이 후덜덜..\n페온30님 궁금한게 있어서 그런데 혹시 전화한번 부탁드려도 될까요?',
  '쪽지로 제전화번호 보내드릴게요!',
  '엔진 오일 교체 후기도 기대되네요..\n지난주에 김포쪽 정비소에서 비중을 약 -27도로 조정했는데요..\n페온30 님은 몇도로 하셨나요?',
  '약 유튜브에 나오듯 약 -10도 인가요?',
  '^^ 지금 겨울철을 앞두고있어서 그런듯 한데요..-10정도에 맞추었습니다.',
  '-5가에 맞춘다고 해도 -5도에 냉각수가 절대 얼지 않는다고 하시고요 페온30 경기김포아... 감사합니다.',
  '저도 온도를 더 낮추어봐야 겠네요.. ^^ 루이스 경기고양자가정비 하실분들은..\n1.',
  '비중계 저도 이제 구매해야 할듯 하구요^^\n2. ph농도측정기 또는 리트머스 용지 그리고 ph 보정액도 하시면 되실듯 합니다.',
  '저도 앞으로 부동액은 이제 자가로 계절 변화시 서서히 해보려고요..  \n그런데 부동액 순환세척은 자가정비가 어려우니 센터를 찾아야 겠지요\n\n권샘 말씀은 냉각수가 아주 심각하지 않는 이상 교환필요없고, 세척제 쓰지말고, 필터링하는 장비로 순환세척만 하면된다고 하셨습니다 페온30 경기김포자세한 설명 감사합니다.',
  '찾아보니 비중계 가격은 저렴하네요..\nph농도측정기는... 음.. 일단 리트머스 용지로... ^^\n보정액은 일단 몰라서 좀 알아봐야 겠네요.. 좋은정보 감사합니다....\n얼마전 엔진경고등으로 점검 받으니 실화코드 떠서 리콜보증기간이라 정비받았습니다,,\n경고등은 없어졋지만,,,그전보다 좀 나아진건 소리가 미세하게 조용해진것 같은데요,,엑셀밟고 나아가는것은\n아직 좀 답답함이 있습니다,,,\n설명을 너무 잘해주셔서 팍팍 와닿네요,,,, 네 저역시 부동액 정비전에 악셀답답함이 극에 달했습니다.',
  '겨울이 다가오는데...지금은 아주 낮은 알피엠애서도 가속력이 아주 좋아졌습니다.',
  '냉각수가이렇게중요하다니\n정보잘봤습니다\n혹시냉각수볼때교환할부품\n있나요10만k입니다 아닙니다.',
  '다른 부품은 교환하지 않았습니다.',
  '다른 유투브 영상도 많이 보시면 느끼실수 있을듯 합니다.',
  '권샘과 함께한 정비의 가치는 제 입장에서는 단순히 부동액 정비비용 그이상의 정보를 얻은것에 있다고 생각했습니다.',
  '페온30 경기김포많은도움되었습니다 정비의 신세계를 보는 듯 합니다.',
  '4번 엑셀 밟고 뗄때 쿵하는 부분도 냉각수 교환 후 엔진점화효율이 좋아져 없어졌다는 말씀인지요?',
  '네 맞아요..훨씬 좋아집니다.',
  '엔진오일 점도도 좀 낮춰도 된다고 합니다.',
  '5w20, 0w30..등등 있는데..w 앞에 있는 저온 점도 5, 0 은 중요하지 않고요..\nw 뒤에 있는 20, 30 이게 중요한데..우리나라 일반적인 날씨 그리고 지금처럼 겨울이 다가오면..20을 써도 무난할듯 합니다.',
  '저도 다음에는 5w20과 지금 남아 있는 5w30을 섞어서 함 넣어보려고요..분명 좋아질거라 생각합니다.',
  '그런데.위에 소개한 권선생님의 엔진오일은 브랜딩 오일을 쓰신다고 하는데.',
  '(저는 아직 안해봤지만..)\n그 브랜딩 오일은 기존의 엔진오일에 있는 연마제를 완전히 제거한 오일이라..\n엔진피스톤의 활동성이 극히 좋아지는거지요..그래서 차가 엄청 부드러워지고\n이런 변화가 냉각수 비중 조절과 함께 좋은 연료+공기 흡입효율을 만들어 내고 ..\n그러면 흡기 카본의 누적이 줄어들고... 그로 인해 배기 계통에 부담도 줄어든다..라고 하시네요..\n저의 부족한 식견으로는 암튼 동의할만한 내용들이었고요...\n그분 유튜브를 보면 더 많이 확인하실수 있으실듯 합니다.',
  '정말 좋은 정보를 올려주셨네요.',
  '많은걸 배우게 됩니다.',
  '감사합니다^^ 좋은정보 알고 갑니다.'])

In [13]:
kma_sent(15)

(129,
 ['산소 센서, 촉매 효율 저하? 엔진 경고등? 흡기 청소? 의 진실, 직접 경험한 스토리입니다.',
  '저의 알 페 온 증상에 따른 이야기 입니다.',
  '2020년 9월 7일( 월) 저는 올해 초 페 오니 3.0을 입양해서 타 던 중.. 지난주 촉매 효율 저하라는 많은 분들이 경험하신 '
  '엔진 경고등을 만나고 나서!!! 영등포 직 영사업소, 강서 정비사업소를 들러.. 촉매를 갈아야 한다는 소리와 어마어마한 비용에 다시 '
  '한번 놀라고 나서, 평소 그 원인이 무엇이길래?? 갈아도 또 얼마 지나지 않아... 이런 저런 정비를 한다는 소리를 많은 분들에게 서 '
  '들었기에.. 블 로그를 검색해서 촉매를 재생한다는 업소에 전화도 해보고.. 다른 정비 사례도 블 로그로 보고 이래저래 해봐도... 답이 '
  '없어서... 바로 알 페 온 본 카페에 가입을 하고 찾아봐도 다들 어려움을 겪고 계시기에.. 왜 카본이 쌓이지? 왜 흡기가 저렇게 '
  '시커먼 거야? 왜 산소 센서가 오작동을 하는 거야? 끊임없는 궁굼증과 고민 속에서.... 여기 저기 뒤지 던 중...!!! 유 튜브에서 '
  '권 영호 라는 분의 영상을 보게 됩니다.',
  'https: //youtu .be /VAwT4RkU1CY 그리고 하나 더.. 이 영상을 보게 됩니다.',
  'https: //youtu .be /tIahyBcFAPk 그리고 저는 직감적으로 늦음 밤시간 잠도 뒤로한 체 바로 이 분과 이야기를 '
  '해야겠다라고 결심을 합니다.',
  '평상시 저는... 흡기 카본이 왜 그렇게 검게 쌓이는지?.. 대한민국 디젤차가 다 저렇다면 도대체 현 기차는 무엇을 한 것인지? '
  '점화플러그를 갈아도 연료 효율 저하가 왜 생기는지? 부조는 왜 생기는 건지? 흡기 클리닝을 해도 왜 또 쌓이는 건지.. 차는 원래 다',
  '저런 건지.. 라는 여기 모든 분들이 가지고 계신 의문점을 저 역시도 가지고 있었던',
  '터라... 권 영호 샘의 위 영상을 두 편 보고... 결국 그 답은 냉각수에 있음을 알게 되었습니다.',
  '그래서 지난주 금요일 권 영호 선생님이 운영하시는 영호자동차가 군산에서 화성으로 정비사업소 이사를 하셨다는 것을 알게 되었고... 바로 '
  '전화 드려 예약을 한 후에.. 드디어..!! 오늘 권 영호 선생님 화성 정비사업소를 다녀왔습니다.',
  '저를 오래 기다리고 계셨더라구요.',
  '이사한 지 얼마 안 되 서 아직 직원을 못 뽑으셨고, 태풍으로 비도 오고 해서 아무도 없는 터 라, 저와 단둘이 서 정비를 무려 5시간 '
  '동안 이런 저런 이야기를 나누면서 정비를 해 주셨는데요 ( 정비하기 전에 저를 앉혀 놓으시고 2 시간을 정비 학 강의?? ㅋㅋㅋ 를 '
  '먼저 충분히 해 주시네요..',
  '세상에 이런 정비사가 대한민국에 있었던가 싶었습니다~',
  'ㅎㅎ) 마치고 나서 함께 저녁식사를 하면서 그분의 미국 유학시절 이야기부터 정비사들을 대상으로 세미나 강의를 하셨던 내용들 등등을 듣게 '
  '됩니다.',
  '암튼 냉각수를 교환하지는 않았습니다.',
  '냉각수 청소를 필터를 통해서 하면서 비중을 조정하고 ph 농도를 맞추어서 엔진의 온도를 최적화 하는 작업만 3 시간 하였습니다.',
  '( 비중을 맞추면서 PH를 조정하는 것이 결국 그분의 노하우였습니다.)',
  '냉각수 내에 있는 때와 먼지를 필터링하고, 비중계를 함께 보면서 맞춰 주시고, 산도를 조정하여 차의 냉각수가 지나가는 통로에 부식이나 '
  '천공이 생기지 않도록 ph 조절 약품을 통해 농도를 중성에 맞추는 작업을 하였습니다.',
  '( 작업 전 제 차의 이력으로 입양 전에 흡기 청소, 점화 플러그 교체.. 써 모스 텟 교체 등 그리고 입양 후 지난주 엔진 오일 '
  '5W30 교 체, 밧데리 최근 교체.. 등을 말씀드렸고요...)',
  '그 결과는 놀라웠습니다.',
  '작업중에도 엔진이 부드러워 지는 것을 샘과 함께 느낄 수 있었습니다.',
  '맞다고',
  '하시네요.',
  'ㅎㅎ 엔진의 온도가 낮아 지니.. 여러 가지로 차가 부드러워 졌습니다.',
  '정비를 마치고 제 차로 선생님과 함께 식당으로 이동하면서도 함께 느끼고.. 식사를 마치고 김 포 집을 오면서 약 50km 정도 운행을 '
  '하면서 느낀 점은 진작에 왜 이런 걸 우리는 몰랐을까',
  '였습니다',
  '1. 일단 온도계 이지의 바늘이 예전보다 낮은 지점에 있다.',
  '2. 변속시 충격이 거의 없어 졌다.',
  '변속 타이밍이 좋아졌습니다.',
  '( 변속 시 알 피엠이 줄어들었다.)',
  '3. 예전에는 악셀을 밟아도 느린 반응으로 인해서 늘 끼어들기를 허용하는 관용을 배 풀었는데요~ ㅋㅋ 이제는 낮은 RPM에서도 끼어들기 '
  '허용? 오늘 하루는 일단 용납을 안했습니다~',
  '즉, 가속력이 좋아졌다는 거죠?',
  '4. 또 제가 지난달 언젠가 부터 저속에서 악셀을 떼면 퉁! 다시 밟으면 퉁! 이렇게 악셀을 밟고 놓을 때마다 퉁퉁 하는 충격이 '
  '있었거든요.. 이것이 저는 엔진 마운팅 볼트( 미 미) 의 불량으로 생각을 해 본적도 있었는데.. 제가 느낀 것은 엔진 점화 효 울 '
  '상승으로 악셀을 밟고 뗄 때나 브레이크를 밟고 뗄 때의 엔진반응이 아주 좋아졌다는 것을 느낄 수 있었습니다.',
  '5. 아직은 더 지켜봐야 하지만 엔진 경고등 뿐 아니라 어떤 고장 코드도 안 뜬다 입니다.',
  '몰론 더 지켜봐야 하겠지만요.... 여기서 잠시! ** 비용을 제가 말씀 못 드리는 것이.... 비용은 비교적 좀 됩니다.',
  '그러나!! 그 분이 5시간 동안 저에게 말씀해 주신 내용은 그 이상의 가치를 저는 받았다고',
  '생각을 하기에 아깝다고',
  '생각하지는 않습니다.',
  '연비가 좋아지고, 다른 곳 고장 안 나면 저는 충분히 그 가치를 했다고',
  '생각해서요~ ㅎ** 권 선생님의 말씀.. " 냉각수는 옷, 엔진 오일은 피 우리나라처럼 따듯한 나라에서 -45도에 맞춘 5:5 비중의 '
  '냉각수는 열대지방에서 겨울옷을 입고 있는 것과 같다.',
  '그러면 체온을 유지하기 위해 얼마나 많은 산소와 땀을 흘리면서 생활을 하겠어요....',
  '그 옷을 벗어 던지지 않으면 모든 병의 근원이 된다" 사진은 정비 후 50km 운행 후에 제 계기판 사진입니다.',
  '제가 예전 사진이 없는데.. 지금 여러분들의 계기판의 온도와 얼마나 다른가요?',
  '읽어 주셔서 감사합니다.',
  '권 영호 정비사업소는 경기도 화성 시 봉 담음 수기리 125-7 http: //naver .me /FjrWGWsp '
  '031-468-0188 / 010.4781-0302 9월 8일( 수) 둘째 날 경험 저는 그냥 서울 테헤란로에서 근무하고 있는 평범한 '
  '일반인인데요.~',
  'ㅎ 그동안 우리가 알고 있던 모든 증상의 90% 는 냉각수와 엔진 오일에 있었네요..',
  '제가 오늘도 차를 타면서 느낀 점은.. 고작 냉각수 하나 건드려서. 비중조정과 PH 중성화 하여 . 엔진 온도를 낮춘 것 뿐인데.. '
  '브레이크 작동, 미션 작동, 가속능력, 변속 충격 등 모든 것이 좋아졌습니다.',
  '이런 노하우를 우리 모든 회원들이 함께 공유했으면 하는 바 랩입니다.',
  '불완전 연소, 카본, 촉매, 산소 센서 등에서의 신호는 모두 엔진 온도 상승으로 인한 결과물이었던 거 였다는 건데요 이번 주는 어제 '
  '정비 후 연비를 측정해 보고 있고요...',
  '다음달 다시 권 영호 샘 방문해서 엔진 오일도 함 갈아 보려 합니다',
  'ㅎㅎ 촉매 이상, 시동이상 등등 괜한 코일, 플러그, 센서, 촉매 비싼 돈 주고 교환하기 전에 꼭 한번 해보세요..',
  '진짜 대박입니다요~',
  'ㅎㅎ 하루빨리 수많은 미해결 증상이 없어 질 그날을 위해 공유하겠습니다',
  '오~! 제 목 보고 들어와 봤는데요.. 저는 이어 시 타고 팄 는데 혹시나 가봐도 될지 모르겠네요..',
  '저도 요즘 페온이가 조금 엑셀을 밟을 때 뭔 가 철사가 끊어지는 듯한 느낌의 소리(?) 가 나는 게 조금 느껴져서요.. 진짜 너무 할 '
  '말이 많은데요.. 꼭 함 가보 세요... 김 포에서 왔다 던 제이야기를 하면 아실 겁니다.',
  'ㅎㅎㅎ 귀한 정보 감사합니다.',
  '저도 함 해보겠습니다.',
  '냉각수 중요성 맞습니다',
  '냉각수라인 청소와 농도를 다시 맞추는 작업이겠네요',
  '미션 오일도 냉각수 라지에 이 터를 통해서 냉각/ 가열되니까 미션 성능과도 상관 있지 않을까',
  '하는 뇌 피 셜입니다',
  'ㅎㅎ 쉐보레차는 냉각수 온도가 높아서 100 도를 넘는 경우가 많다는 글이 많아서 그런가 부다 했는데 제차 확인해 보니 85도에서 '
  '상당히 가혹하게 달려도 100 도가 안된다는 걸 확인한 후 의문점이 생겼습니다만 저처럼 낮은 경우가 별로 없는 듯해서 오히려 제차가 '
  '이상한 가 생각도 하게 되네요',
  'ㅎ ㅎㅎ 네 맞습니다.',
  '냉각수 고무관에 붙은 때를 벗기면 냉각 효율이 좋아진다고 합니다.',
  '냉각수는 교환하는 것이 아니라 순환기를 통해 청소만 하면 된다고 하시고.. 실제 청소 후 맑은 홍차가 되더라',
  '고요 엔진 온도가 낮 으면 각종 고무 부품의 부풀어오름과 경화를 방지하게 되니 이 역시 비용 절감.. PH 농도가 낮아서 산성이 '
  '되면.. 부식과 천공이 생기고..( 뇌 출혈 ㅋㅋㅋ) PH 농도가 높아서 알칼리가 되면 혈전이 쌓이게 되 서..( 동 맥 경화.) 이런 '
  '거라고 하시네요',
  '그래서 한국 기후에 맞는 농도도 중요 하심 나 PH 농도 역시 부품의 내구성과 유지에 아주 중요 하다는 말씀도 함께 들었습니다.',
  '실제 맞고 공감하는 내용들이었습니다~',
  'ㅎ 좋은 글 잘 봤습니다.',
  '가보고 싶은 마음이 저절로 드네요.',
  '혹시 비용이 얼마인지 일수 있을까요',
  '직접 전화해 보시면 알려 주실 겁니다',
  '^^ 저도 그랬거든요... 냉각수 관리 중요합니다.',
  '전 예전 차에 냉각수 교환 및 크리닝으로 전체적인 효과를 봐서 그런지 냉각수 중요하다 생각 드네요.',
  '물론 페온이도 관리를 잘 해서 그런지 작년에 중고로 가져와 알 피엠 풀로 다녀도 아직 경고등 한번 본적이 없네요.',
  '좋은 글이네요.',
  '냉각수와 오일 류만 잘 관리해도 8할은 먹고 가는 거죠.',
  '안전 운전 하세요~ 성의 있는 후기 잘 보았습니다',
  '회원 님 들이 냉각수 중요성을 많이 알게 될 것 같습니다',
  '저도 엔진 출력부족 부조 꿀렁임 관련해서 이미 앞전에 방문해서 점검 받았고 견제 받았네요',
  '그런데 금액이 후 덜덜.. 페 온 30 님 궁금한 게 있어서 그런데 혹시 전화 한번 부탁드려도 될까요?',
  '쪽지로 제 전화번호 보내',
  '드릴게요!',
  '엔진 오일 교체 후기도 기대되네요..',
  '지난주에 김 포 쪽 정비소에서 비중을 약 -27 도로 조정했는데요.. 페 온 30 님은 몇 도로 하셨나요?',
  '약 유 튜브에 나오듯 약 -10도 인가요?',
  '^^ 지금 겨울철을 앞두고 있어서 그런 듯 한데요 ..-10 정도에 맞추었습니다.',
  '-5 가에 맞춘다고 해도 -5도에 냉각수가 절대 얼지 않는다고',
  '하시고요',
  '페 온 30 경기 김 포 아... 감사합니다.',
  '저도 온도를 더 낮추어 봐야 겠네요..',
  '^^ 루이스 경기 고양 자가 정비 하실 분들은.. 1. 비중계 저도 이제 구매해야 할 듯 하구요',
  '^^ 2. ph 농도 측정기 또는 리트머스 용지 그리고 ph 보정 액도 하시면 되실 듯 합니다.',
  '저도 앞으로 부동액은 이제 자가로 계절 변화시 서서히 해보려고요.. ㅎㅎ 그런데 부동액 순환 세척은 자가 정비가 어려우니 센터를 찾아야 '
  '겠지요 권 샘 말씀은 냉각수가 아주 심각하지 않는 이상 교환 필요없고, 세척제 쓰지 말고, 필터링하는 장비로 순환 세척만 하면 된다고 '
  '하셨습니다',
  '페 온 30 경기 김 포자세한 설명 감사합니다.',
  '찾아보니 비중계 가격은 저렴하네요..',
  'ph 농도 측정기는... 음.. 일단 리트머스 용지로... ^^ 보정 액은 일단 몰라서 좀 알아봐야 겠네요..',
  '좋은 정보 감사합니다....',
  '얼마 전 엔진 경고등으로 점검 받으니 실화 코드 떠서 리콜보증기간이라 정비 받았습니다,,',
  '경고등은 없어졋지만,,, 그 전보다 좀 나아진 건 소리가 미세하게 조용 해진 것 같은데요,, 엑셀 밟고 나아가는 것은 아직 좀 답답함이 '
  '있습니다,,,',
  '설명을 너무 잘해 주셔서 팍팍 와닿네요,,,,',
  '네',
  '저 역시 부동액 정 비전에 악셀 답답함이 극에 달했습니다.',
  '겨울이 다가오는데... 지금은 아주 낮은 알 피엠 애서도 가속력이 아주 좋아졌습니다.',
  '냉각수가 이렇게 중요하다니',
  '정보 잘 봤습니다',
  '혹시 냉각수 볼 때교환할 부품 있나요',
  '10만 k 입니다',
  '아닙니다.',
  '다른 부품은 교환하지 않았습니다.',
  '다른 유 투브 영상도 많이 보시면 느끼실 수 있을 듯 합니다.',
  '권 샘과 함께 한 정비의 가치는 제 입장에서는 단순히 부동액 정비비용 그 이상의 정보를 얻은 것에 있다고',
  '생각했습니다.',
  '페 온 30 경기 김 포 많은 도움되었습니다',
  '정 비의 신세계를 보는 듯 합니다.',
  '4번 엑셀 밟고 뗄 때 쿵 하는 부분도 냉각수 교환 후 엔진 점화 효율이 좋아져 없어 졌다는 말씀인지요?',
  '네',
  '맞아요..',
  '훨씬 좋아집니다.',
  '엔진오일 점도도 좀 낮춰도 된다고 합니다.',
  '5w20, 0w30.. 등 등 있는데 ..w 앞에 있는 저온 점도 5, 0 은 중요하지 않 고요.. w 뒤에 있는 20, 30 이게 '
  '중요한 데.. 우리나라 일반적인 날씨 그리고 지금처럼 겨울이 다가오면 ..20 을 써도 무난할 듯 합니다.',
  '저도 다음에는 5w20 과 지금 남아 있는 5w30 을 섞어서 함 넣어 보려고요.. 분명 좋아질 거라',
  '생각합니다.',
  '그런 데. 위에 소개한 권 선생님의 엔진 오일은 브랜딩 오일을 쓰신다고 하는데.( 저는 아직 안 해봤지만..) 그 브랜딩 오일은 기존의 '
  '엔진 오일에 있는 연마제를 완전히 제거한 오일이라.. 엔진 피스톤의 활동성이 극히 좋아지는 거지요.. 그래서 차가 엄청 부드러워 지고 '
  '이런 변화가 냉각수 비중 조절과 함께 좋은 연료+ 공기 흡입 효율을 만들어 내고 .. 그러면 흡기 카본의 누적이 줄어들고... 그로 '
  '인해 배기 계통에 부담도 줄어든다 ..라고 하시네요..',
  '저의 부족한 식견으로는 암 튼 동의할 만한 내용들이었고요...',
  '그분 유 튜브를 보면 더 많이 확인하실 수 있으실 듯 합니다.',
  '정말 좋은 정보를 올려 주셨네요.',
  '많은 걸 배우게 됩니다.',
  '감사합니다',
  '^^ 좋은 정보 알고 갑니다.'])

In [14]:
sentences(4)

(13,
 ['1986 chevrolet caprice brougham1986 쉐보레 카프리스 브로엄!!',
  '사각 헤드라이트가 옹골찬 느낌입니다.',
  '헬리콥터 시점   \n차단봉(?',
  ')이 좀 높군요.',
  '페라리같은 낮은차들은 그냥 지나갈듯...\n트렁크 리드도 길고 안락해보이네요.',
  '요즘차들은 실내 공간을 길게 뽑으려고 트렁크리드가 저렇게까지 길진 않지요.',
  '사각사각!!',
  '80년대 감성 미국차의 전형적인 뒷태군요.',
  '보정한 사진입니다.',
  '필름효과가 3가지나 있네요~와.. 각진차체.. 맘에듭니다 각이 살아있습네다!!',
  '그린라이트가 라이트류만 클리어 처리해준다면 정말 갑이될수\n있을거 같네요\n\n그리고 차량 너무 멋집니다~!!',
  '저게 그린라이트답죠.',
  '클리어 처리는 안 어울릴거 같아요.'])

In [15]:
kma_sent(4)

(12,
 ['1986 Chevrolet Caprice Brougham1986 쉐보 레 카프 리스 브로 엄!! 사각 헤드라이트가 옹골찬 느낌입니다.',
  '헬리콥터 시점 ㄷ ㄷ 차단 봉(?) 이 좀 높군요.',
  '페라리 같은 낮은 차들은 그냥 지나갈 듯... 트렁크 리드도 길고 안락해 보이네요.',
  '요즘 차들은 실내 공간을 길게 뽑으려고 트렁크 리드가 저렇게 까지 길 진 않지요.',
  '사각사각!! 80년대 감성 미국 차의 전형적인 뒷 태 군요.',
  '보정한 사진입니다.',
  '필름효과가 3가지나 있네요~',
  '와.. 각진 차체.. 맘에 듭니다',
  '각이 살아있습네다!! 그린 라이트가 라이트 류만 클리어 처리해 준다면 정말 갑이 될 수 있을 거 같네요',
  '그리고 차량 너무 멋집니다~!!',
  '저게 그린 라이트답죠.',
  '클리어 처리는 안 어울릴 거 같아요.'])

In [16]:
sentences(11160)

(1,
 ['nan입력 20200702 0753 미국의 전기자동차 기업인 테슬라가 시가총액 세계 1위 자동차 업체에 등극했다 1일현지 시각 블룸버그 통신은 테슬라가 세계 최대 완성차업체 중 하나인 일본 도요타자동차를 제치고 시가총액 1위에 올라섰다고 보도했다 2010년 6월 나스닥시장에 상장한 지 10년여 만이다블룸버그는 이와 관련해 130여년간 내연기관엔진 중심이었던 자동차 산업이 전기차로 이동하는 가운데 그 변화를 이끄는 테슬라에 투자자들이 열광하고 있다고 보도했다테슬라 주가는 이날 장중 4 넘게 올라 주당 1130달러를 넘어섰다 이와 함께 시가총액은 2090억달러약 251조원를 돌파했다 테슬라 주가는 올들어 이날까지 두 배 이상 뛰었다 반면 도요타 주가는 1일 도쿄증시에서 15 떨어진 6656엔으로 마감했다 시가총액 22조405억엔약 2050억달러로 장을 마쳤다테슬라는 올 1분기에 총 10만3000대를 생산했다 도요타가 생산한 240만대의 4밖에 되지 않는다 도요타는 하이브리드카를 세계 최초로 개발해 상용화했고 이후에는 전기차 대신 수소전기차에 역량을 집중해 왔다 최근에는 전기차 개발에도 힘을 쏟고 있다일각에선 테슬라가 도요타를 시총에서 앞선 것을 두고 2015년 아마존이 월마트를 추월한 사건과 비교하며 높이 평가하고 있다 한편 테슬라의 최고경영자ceo인 일론 머스크는 자동차 업계의 수많은 규칙과 관행을 깨뜨린 인물로 평가를 받는다 인건비가 높은 캘리포니아에 공장을 마련하는가 하면 딜러 중심의 미국 자동차 유통망을 무시하고 온라인으로만 판매하는 전략을 고수하는 것이 대표적이다'])

In [17]:
kma_sent(11160)

(4,
 ['nan 입력 20200702 0753 미국의 전기자동차 기업인 테슬라가 시가 총액 세계 1위 자동차 업체에 등극했다 1일 현지 시각 '
  '블룸 버그 통신은 테슬라가 세계 최대 완성 차업체 중 하나 인 일본 도 요타자동차를 제치고 시가 총액 1위에 올라 섰다고 보도했다 '
  '2010년 6월 나스닥시장에 상장한 지 10년 여 만이다',
  '블룸 버그는 이와 관련해 130여년 간 내연기관 엔진 중심이었던 자동차 산업이 전기 차로 이동하는 가운데 그 변화를 이끄는 테슬라에 '
  '투자자들이 열광하고 있다고',
  '보도했다 테슬라 주가는 이날 장 중 4 넘게 올라 주당 1130 달러를 넘어섰다 이와 함께 시가 총액은 2090억 달러 약 251조 '
  '원를 돌파했다 테슬라 주가는 올 들어 이날까지 두 배 이상 뛰었다 반면 도요 타 주가는 1일 도쿄 증시에서 15 떨어진 6656엔으로 '
  '마감했다 시가 총액 22조 405억엔 약 2050억 달러로 장을 마쳤다 테슬라는 올 1 분기에 총 10만 3000대를 생산했다 도요 '
  '타가 생산한 240만 대의 4밖에 되지 않는다 도요 타는 하이브리드 카를 세계 최초로 개발해 상 용화했고 이후에는 전 기차 대신 수소 '
  '전 기차에 역량을 집중해 왔다 최근에는 전 기차 개발에도 힘을 쏟고 있다 일각에선 테슬라가 도 요타를 시 총에서 앞선 것을 두고 '
  '2015 년 아마존이 월 마트를 추월한 사건과 비교하며 높이 평가하고 있다 한편 테슬라의 최고 경영자 CEO 인 일론 머스크는 자동차 '
  '업계의 수많은 규칙과 관행을 깨뜨린 인물로 평가를 받는다',
  '인건비가 높은 캘리포니아에 공장을 마련하는 가 하면 딜러 중심의 미국 자동차 유통망을 무시하고 온라인으로만 판매하는 전략을 고수하는 '
  '것이 대표적이다'])

In [18]:
sentences(10000)

(1,
 ['내가 앞장섰다내가 앞장섰다국가로서의 자유 의지의 산성은 도시 시대와 더욱 결속되었다성원균은 자동차 배기가스 관련 학술연구환경 보존과 함께 자동차연구 환경을 제공하고 있으며 풍년천인단 80기 개발단계에서는 하천과 하천이 하나로 통일되어 에럽브룩사의 중요성이 증대되고 있다 도시두부 부엌문화 여백 바깥의 흙 속으로 태봉이 들어가고 끝끝내 눈물이 난다물론 중국의 붕괴는 중국을 불안하게 만든다그는 또한 그를 세계에서 가장 영향력 있는 인물 중 한 명으로 꼽았다전부도시의 이유와 남녀관계 등이 꾸며졌다뱃속에 풀이 있는 관절연장과 관절연장이 있다기자가 들어왔다어촌인 한산도는 우리 리넨으로 만든 가족 중 대한민국 하달한팔리의 토양오염에 좋은 70여 점의 노벨상을 사용하기 위해 남쪽에 정차한다냄비를 끓이다구조는 그에 따라 평가된다그루트fdjblf 너트06 선빗무늬토기 프리 빗살무늬토기  i기빗무늬토기가 대표적이다서사시로서도 출판되었다매카트니와 담배가 없는 것은 아니었지만 거절의 일차적인 반찬 때문에 충녕대군을 돕기 시작했다기술은 1096개의 수곡에 갇힌 두리안을 도시화하면서 식품이 발전하고 우리가 살균하는 다른 전기의 관리를 통해 모든 겨울 지배자를 배출한 것으로 추정하고 있다많은 사람들과 많은 사람들이 덩굴의 신전을 반대했다  이는 성령 보리쌀을 용기에서 삼국지 부근까지 운반하였기 때문에 태양의 특징이다세종대왕의 확산에 따른 2015년 전망 변화 스토리와 2015년 전망 변화 스토리가 마사지되는 농촌에서 상비약 명칭은 통용고성가산유향산원으로 제2차 경제발전을 앞두고 남녀로 나뉘어 있다rganianti 지역은 둥근 왜소      세포에 설탕을 넣어 여름 음식에 대해 사과한다 1989년 매우 빠른 그룹에 속했던 바로 그 그룹이다그럴 만한 가치가 있다모히토 시대에는 옛이야기라 인간이 분열되어 있다캐나다는 끓어오르는 역사를 동반했다우리의 조건이 정해졌을 때 청구되었다1971년 과일이 달성되었고 중앙아시아 내몽골 동몽골 진국 진적 부여 부여 부여 부여 부여 부여 부여 부여 부여 부여 부여 부여 부여 부여에서 먹는 과일은 주사위로 축적되어 폭우요법으로 인한 잎이 축적되었다신석기 시대의 가장 긴 고추는 불상이 아니라 자치도시에 정확히 위치해 있었다노란색 범주가 얕고 배타적인 방식으로 표시되는 국가 또는 국가그것은 회원들의 것이다많은 조교들과 마찬가지로 정약용씨도 한국 전통음악을 좋아하지만 어장을 보존하기 위한 당포와 당포의 수가 유입되고 있는 집중호우도시에는 연구자가 많다이들의 부인이었던 기록물 목록은 도내 brdjtfdt가 발굴한 국가정책의 종류와 생산패턴 등을 토대로 작성됐다 당초 바인더 수는 늘고 문화 질은 높아졌지만 8월에는 빨간색이 추가됐다그 강도 외에도 1883년 수나라에는 세계 시장에서 그림을 그리려는 노력을 하지 않으려는 노력도 있었다특히 본관이나 본관은 독특하다미국 삼국시대에는 이미 10분이 지났지만 뒤처지고 있었다그랬어열두 살이 되었을 때 그는 발길을 돌렸다셋째 그 이름으로 고 강남농업법무관과 가깝다준비 작업이 문제다 동해의 생각 중 중기에다른 주의 유성룡은 1776년 경상도로 흘러들어온 눈꺼풀이 발달했고 진골귀족은 발달하기 위해 술집에서 여성을 공격하려 했다남은 쌀을 육지로 가져왔지만 그는 알지 못했다각 평가의 차이는 계속되었고 제2기가 되어서야 황제의 물 전쟁이 유배지에서 발발하여 왕위와의 유대가 약화되었다그 말은 1971년에 태어났다'])

In [ ]:
kkma()

# 29새벽 함수 만들기 테스트|

In [1]:
def totest(hello):
    hello+'world' = list()
    
    return hello+'world'

SyntaxError: can't assign to operator (<ipython-input-1-3f9bde661d03>, line 2)

In [16]:
def classify(string):
    
    def count_values(series):
        items=[]
        for item in series.value_counts().items():
            items.append(item)
        neg, pos = items[0][1] / (items[0][1] + items[1][1]), items[1][1] / (items[0][1] + items[1][1])

        return 'negative : {0}%, positive : {1}%'.format(neg, pos)
    
    string2df = awarness[awarness['all_text'].str.contains(string, na = False)]
    kwd_labels = []

    cnt = 0
    testlen = mileage.shape[0]
    for i in range(testlen-1):
        
        try:
            labeled = test_sentences([string2df['all_text'].iloc[i]])
            kwd_labels.append(np.argmax(labeled))
        except:
            kwd_labels.append('Nan')

        cnt += 1
        if cnt%200==0:
            print('{0:.2f}% complete'.format((cnt/testlen)*100))

    print('done')

    labelseries = pd.Series(kwd_labels)
    
    return count_values(labelseries)

In [36]:
import pandas as pd
ttest = pd.Series([1,0,1])

def count_values(series):
    items=[]
    for item in series.value_counts().items():
        items.append(item)
    if items[0] == 0:
        neg, pos = items[0][1] / (items[0][1] + items[1][1]), items[1][1] / (items[0][1] + items[1][1])
    else:
        pos, neg = items[0][1] / (items[0][1] + items[1][1]), items[1][1] / (items[0][1] + items[1][1])
    
    return 'negative : {0}%, positive : {1}%'.format(neg*100, pos*100)

In [17]:
classify('tteset')

NameError: name 'awarness' is not defined

In [10]:
count_values(ttest)

'negative : 0.7%, positive : 0.3%'

In [50]:
ttest = pd.Series([1,0,1,1,1,1,1,1])
#ttest = pd.Series([1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

In [51]:
ttest.value_counts()

1    7
0    1
dtype: int64

In [52]:
tttt=[]
for item in ttest.value_counts().items():
    tttt.append(item)
tttt

[(1, 7), (0, 1)]

In [55]:
tttt[0][1] / (tttt[0][1] + tttt[1][1] )

0.875

In [45]:
# ttest = pd.Series([1,0,1,1,1,1,1,1])
ttest = pd.Series([1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

In [46]:
ttest.value_counts()

0    18
1     7
dtype: int64

In [47]:
items=[]
for item in ttest.value_counts().items():
    items.append(item)
items

[(0, 18), (1, 7)]

In [48]:
items[0][1]

18

In [24]:
items=[]
for item in ttest.value_counts().items():
    items.append(item)
items

[(1, 8), (0, 7)]

In [34]:
count_values(ttest)

'negative : 22.22222222222222%, positive : 77.77777777777779%'

In [ ]:
pos, neg = 0, 0
for item in ttest.value_counts().items():
    items.append(item)

if items[0] == 0:
    neg, pos = items[0][1] / (items[0][1] + items[1][1]), items[1][1] / (items[0][1] + items[1][1])
else:
    pos, neg = items[0][1] / (items[0][1] + items[1][1]), items[1][1] / (items[0][1] + items[1][1])

In [7]:
items[0][1] + items[1][1]

10

In [8]:
neg = items[0][1] / (items[0][1] + items[1][1])
neg

0.7